Use Kotlin DSL for builder functions
eclipse-uprotocol/up-kotlin pull request #19
Opened 2024-03-01 21:35 UTC by mikaelperrin

Replace UAttributesBuilder with Kotlin DSL type safe builder functions 
Replace UResourceBuilder with Kotlin DSL type safe builder functions 
Update UCloudEventAttributes to use Kotlin DSL type safe builder instead 
Replace CallOptionsBuilder with Kotlin DSL type safe builder instead

Fixes #10

2024-03-01 21:36 UTC, mikaelperrin commented
Waiting for #18 to be merged to rebase this one.

2024-03-07 20:52 UTC, dddj698 requested changes

2024-03-07 20:52 UTC, dddj698 commented on src/main/kotlin/org/eclipse/uprotocol/v1/UAttributesKtExt.kt
> +}
fun UAttributesKt.Dsl.forResponse(responseSource : UUri, responseSink: UUri, uPriority: UPriority,  reqId: UUID) {
    source = responseSource,
    id = UUIDV8()
    type = UMessageType.UMESSAGE_TYPE_RESPONSE
    priority = uPriority
    sink = responseSink
    reqid = reqId
}

2024-03-07 20:52 UTC, dddj698 commented on src/main/kotlin/org/eclipse/uprotocol/v1/UAttributesKtExt.kt
> +@JvmSynthetic
source needs to be added to attributes, 
also for consistency, move sink before priority.

2024-03-11 21:46 UTC, closed without merging